### ISSUE TITLE
클라이언트 Observable 개선

### ISSUE THREAD

**Issue by dongqui** [woowa-techcamp-2021/cashbook-12#14]
## 개요 
- 컴포넌트가 new 될 때 마다 handlers에 callback이 계속 쌓이는 문제가 있습니다.
## 소요 시간 

- 예상 완료 시간 : 2h
- 실제 투입 시간 : 

## 진행 사항 

- [x] observable 내부에 불필요한 핸들러 제거
- [x] 기본 기능 유지
- [ ] 이벤트 처리 개선

**Comment by Seogeurim** [comment]
컴포넌트 구조가 바뀌어 이슈 close하겠습니다 !
