### ISSUE TITLE
차트 페이지 이동시 깜빡임

### ISSUE THREAD

**Issue by dongqui** [woowa-techcamp-2021/cashbook-12#34]
## 개요 
차트 페이지로 이동시 간헐적으로 깜빡임이 있습니다.

## 버그 발생 단계 

1. 아무 페이지로 들어갑니다
2. 차트 탭 클릭

## 예상 동작 
깜빡이지 않고 깔끔하게 페이지 이동

## 진행 사항 

- [ ] 페이지 이동시 깜빡임 x

**Comment by dongqui** [comment]
이거 무슨 일인지... 자동으로 해결 됐네요!?ㅋㅋ 👍

**Comment by dongqui** [comment]
@Seogeurim

**Comment by Seogeurim** [comment]
오잉 ?! ㅋㅋㅋㅋㅋㅋㅋ 사실 저도 깜빡임이 없어서 뭘까 생각하고 있었습니당 ㅎㅎㅎ 다행이에요 ㅎㅎ 호호
